services:
  backend:
    container_name: 'backend'
    build: ./backend
    restart: always
    ports:
      - "8080:3000"
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    container_name: 'frontend'
    build: ./frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  db:
    container_name: 'database'
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tripdb
    ports:
      - "5433:5432"
    volumes:
      - ./backend:/docker-entrypoint-initdb.d
    networks:
      - app-network

volumes:
  postgres_data:
    driver: local

networks:
  app-network:
    driver: bridge
